// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Aranya",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Aranya",
            targets: ["NatureCompanionApp"],
            bundleIdentifier: "com.akhand.naturecompanion",
            teamIdentifier: "6UKXU9X84Z",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .flower),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.phone]))
            ],
            capabilities: [
                .camera(purposeString: "We need the camera to capture nature objects."),
                .microphone(purposeString: "We need the microphone to hear your voice."),
                .photoLibrary(purposeString: "We need access to photos to upload images."),
                .speechRecognition(purposeString: "We use speech recognition to talk to nature.")
            ],
            appCategory: .productivity
        )
    ],
    targets: [
        .executableTarget(
            name: "NatureCompanionApp",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)